### ISSUE TITLE
Changing Static Directory for System Templates

### ISSUE THREAD

**Issue by candideu** [knadh/listmonk-heroku#1]
Hello! I used the Heroku deploy button and that worked perfectly. However, I want to edit/update the system templates and I'm not sure how to proceed with a Heroku installation. From what I understand, I have to change the [Listmonk static directory using the command line](https://listmonk.app/docs/templating/#system-templates), but I'm not sure how to do this on Heroku...

**Comment by knadh** [comment]
I'm not very familiar with how Heroku instances work, but you should check the Heroku docs on mounting filesystems. I do think that the deployment via the button may not be customizable given the ephemeral nature of Heroku dynos. You may have to write your own deployment with a mounted filesystem.

**Comment by candideu** [comment]
> 
> 
> I'm not very familiar with how Heroku instances work, but you should check the Heroku docs on mounting filesystems. I do think that the deployment via the button may not be customizable given the ephemeral nature of Heroku dynos. You may have to write your own deployment with a mounted filesystem.

Sounds good, thank you for your quick response @knadh!

How can I write a deployment with a mounted filesystem? I was able to get the Listmonk binary running on my Windows PC with the localhost and using `--static-dir=`, but had trouble with Docker (it was my first time using it). That said, I wouldn't want the files to be on my computer's localhost, but online so that the signup form can be filled out by anyone.

Can the binary be launched on some other kind of online server? Do you have any recommendations?

**Comment by knadh** [comment]
> How can I write a deployment with a mounted filesystem?

You'll have to look at Heroku docs and tutorials!

> Can the binary be launched on some other kind of online server? Do you have any recommendations?

Of course. A small instance on AWS EC2 or DigitalOcean or any such host will do. SSH into the instance, install and run Postgres, download and run the listmonk binary (preferably as a  background [systemd service](https://github.com/knadh/listmonk/blob/master/listmonk%40.service)). This is how you would run any app. You can Google and figure out how to run binaries on servers via SSH.

**Comment by candideu** [comment]
Thank you for your continued help and quick replies @knadh! I've Google everything you sent, but unfortunately, it's beyond my current scope of knowledge. I think I'll stick to the Heroku deployment option and current layout for the static pages. Hopefully, there will be a way in the future to modify these static page templates from within the program the same way we can create campaign templates and add our logo/favicon.

Thanks again for your help and for this fantastic software!
