### ISSUE TITLE
Deploy failed.

### ISSUE THREAD

**Issue by srikanthlogic** [knadh/listmonk-heroku#3]
App creation failed. Please ensure you have valid values in the above form fields.

A red toast comes up with

> We couldn't deploy your app because the source code violates the [Salesforce Acceptable Use and External-Facing Services Policy](https://a.sfdcstatic.com/content/dam/www/ocms-backup/assets/pdf/misc/ExternalFacing_Services_Policy.pdf).

![image](https://user-images.githubusercontent.com/126862/150669192-76780cd1-8c06-45f0-b713-0649bda24196.png)

**Comment by knadh** [comment]
Please see https://github.com/knadh/listmonk/issues/661

I'll try and speak to Heroku to figure out why the repo is being flagged.

**Comment by bajpaia** [comment]
well what happened?

**Comment by knadh** [comment]
No idea. Heroku's disallowed listmonk.

**Comment by RitvikSardana** [comment]
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

I am also receiving the same error
Can anyone help?

**Comment by organicnz** [comment]
Confirming. Facing the same issue today.

**Comment by peteryang1756** [comment]
> 確認。今天面臨同樣的問題。
heroku is no longer free in the future, Welcome to try out this free deployment Listmonk https://github.com/railwayapp-starters/listmonk

**Comment by knadh** [comment]
Heroku seems to have blanket banned mailing list apps.

**Comment by organicnz** [comment]
> > 確認。今天面臨同樣的問題。
> > heroku is no longer free in the future, Welcome to try out this free deployment Listmonk https://github.com/railwayapp-starters/listmonk

Confirmed, deployment Listmonk on Railwayapp works fine :)
